### ISSUE TITLE
Color and Palette functionality

### ISSUE THREAD

**Issue by Laguna1989** [Laguna1989/JamTemplateCpp#82]
Colors currently only support rgb.

- [x] hsv2rgb
- [x] rgb2hsv
- [x] Add hexString support  #93 
- [x] Add random functions to get a color with a fixed saturation or hue #100 
- [x] Add Palette class to group colors together and manipulate them together #100 
- [x] Palette from gpl #102 
- [x] Add Demo #102
